"""Add moderation fields to posts and comments

Revision ID: 472c34150ac4
Revises: cbcef27823ba
Create Date: 2025-09-06 10:45:40.126438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472c34150ac4'
down_revision: Union[str, Sequence[str], None] = 'cbcef27823ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'REJECTED', 'SCHEDULED', name='poststatus'), nullable=False))
    op.add_column('blog_posts', sa.Column('moderated_by', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blog_posts', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('blog_posts', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('blog_posts', sa.Column('scheduled_publish', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blog_posts', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('blog_posts', sa.Column('meta_description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'users', ['moderated_by'], ['id'])
    op.add_column('comments', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SPAM', name='commentstatus'), nullable=False))
    op.add_column('comments', sa.Column('moderated_by', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['moderated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'is_spam')
    op.drop_column('comments', 'moderated_at')
    op.drop_column('comments', 'moderated_by')
    op.drop_column('comments', 'status')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'meta_description')
    op.drop_column('blog_posts', 'tags')
    op.drop_column('blog_posts', 'views')
    op.drop_column('blog_posts', 'scheduled_publish')
    op.drop_column('blog_posts', 'featured')
    op.drop_column('blog_posts', 'rejection_reason')
    op.drop_column('blog_posts', 'moderated_at')
    op.drop_column('blog_posts', 'moderated_by')
    op.drop_column('blog_posts', 'status')
    # ### end Alembic commands ###
