version: 2
updates:
  - package-ecosystem: "pip" # for Python project
    directory: "/python"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: auto

  - package-ecosystem: "pub" # for Flutter/Dart project
    directory: "/app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: auto

  - package-ecosystem: "npm" # for Next.js project
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: auto
