version: 2
updates:
  - package-ecosystem: "pip" # for Python project
    directory: "/python" # Specify the directory where your requirements.txt resides
    schedule:
      interval: "daily" # check for updates daily
  - package-ecosystem: "pub" # for Flutter/Dart project
    directory: "/app" # Specify the directory where your pubspec.yaml resides
    schedule:
      interval: "daily" # check for updates daily
