easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  entities:
    # List the entity class name you want to manage
    BlogPost:
      class: App\Entity\BlogPost
      form:
        fields:
          - { property: 'title' }
          - { property: 'author' }
          - { property: 'slug' }
          - { property: 'published' }
          - { property: 'content', type: 'fos_ckeditor'}
