services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: sf5_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ChangeMe123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sf5_network

  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sf5_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./var:/var/www/var
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://app:ChangeMe123@database:5432/app?serverVersion=15&charset=utf8
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
    depends_on:
      - database
    networks:
      - sf5_network

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: sf5_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sf5_network

volumes:
  postgres_data:
    driver: local

networks:
  sf5_network:
    driver: bridge