services:
  # FastAPI Backend (Development)
  api:
    build: ./python
    container_name: blogging-app-api-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./blog.db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - CORS_ORIGINS=["http://localhost:3000", "http://web:3000"]
    volumes:
      - ./python:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - blogging-network

  # Next.js Frontend (Development)
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: blogging-app-web-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_INTERNAL_URL=http://api:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - blogging-network

networks:
  blogging-network:
    driver: bridge