services:
  # FastAPI Backend
  api:
    build: ./python
    container_name: blogging-app-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./blog.db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://web:3000
    volumes:
      - ./python:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blogging-network

  # Next.js Frontend
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: blogging-app-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - API_INTERNAL_URL=http://api:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - blogging-network

  # Optional: PostgreSQL database for production
  db:
    image: postgres:15-alpine
    container_name: blogging-app-db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blogging-network

volumes:
  postgres_data:

networks:
  blogging-network:
    driver: bridge