name: sf5_blog_app
description: A Flutter application to integrate with SF5 Blog API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Shared preferences for local storage
  shared_preferences: ^2.2.2
  
  # State management
  provider: ^6.1.1
  
  # Routing
  go_router: ^12.1.3
  
  # UI components
  cupertino_icons: ^1.0.2
  
  # Theme and UI
  flex_color_scheme: ^7.3.1
  
  # File picker for avatar upload
  image_picker: ^1.0.4
  
  # Network image loading
  cached_network_image: ^3.3.0
  
  # Loading animations and skeleton
  shimmer: ^3.0.0
  
  # Better forms
  flutter_form_builder: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation for JSON
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing dependencies
  mockito: ^5.4.4
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  shared_preferences_test: ^2.1.0

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg