name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, pdo_pgsql, mysqli, pgsql
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: php/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('php/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: php
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run PHPUnit tests
      working-directory: php
      run: php bin/phpunit

    - name: Run PHPStan analysis
      working-directory: php
      run: vendor/bin/phpstan analyse