name: Daily Composer Update

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM UTC
  workflow_dispatch:     # Allows manual triggering from GitHub UI

jobs:
  composer-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust as per your Symfony project
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Update dependencies
        run: composer update --no-interaction

      - name: Commit updated composer.lock
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add composer.lock
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: daily composer update"
            git push origin main
          fi
