name: Quality Gates
on: [push, pull_request]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20.x }
      - run: |
          cd web
          npm ci
          npm run lint
          npm run type-check
          npm run test -- --coverage
          npx playwright install --with-deps
          npx playwright test

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: |
          cd python
          pip install -r requirements.txt
          pytest app/tests -v --cov=app --cov-report=xml
        env:
          TESTING: "true"
          DATABASE_URL: "sqlite+aiosqlite:///./test.db"
          SECRET_KEY: "test-secret"
          JWT_ALG: "HS256"

  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: |
          cd app
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart analyze
          flutter test --coverage