name: Resolve composer.lock conflicts

on:
  push:
    branches:
      - main # Or the branch you want this workflow to run on

jobs:
  update-lock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Important: this is needed for actions/checkout to fetch all branches

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Modify as per your PHP version
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Update composer.lock file
      run: |
        git checkout --ours composer.lock # You can use --theirs instead of --ours based on your preference
        composer update

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Resolved composer.lock conflict"
        git push
